# Generated by Django 4.1.4 on 2023-04-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='following',
            new_name='Follow',
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
