# Generated by Django 4.1.4 on 2023-05-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
